export const dailyTips: string[] = [
  "Drink a glass of water before each meal to help with portion control and hydration.",
  "Pre-portion snacks into containers when you get home from the store to avoid overeating.",
  "Add vegetables to your morning eggs for an extra nutrient boost and fiber.",
  "Marinate proteins overnight in the fridge for deeper flavor and more tender results.",
  "Use a food scale to accurately measure portions—visual estimates are often incorrect.",
  "Meal prep on Sundays: cook grains, roast vegetables, and portion proteins for the week.",
  "Include a source of protein in every meal to help maintain steady energy levels.",
  "Let meat rest for 5-10 minutes after cooking to redistribute juices and improve flavor.",
  "Read nutrition labels focusing on protein, fiber, and added sugars rather than just calories.",
  "Prep a 'snack drawer' at work with nuts, cut vegetables, and protein bars to avoid vending machines.",
  "Toast spices in a dry pan before grinding to unlock their full flavor potential.",
  "Aim for 5-9 servings of fruits and vegetables daily for optimal nutrition.",
  "Use lemon juice or vinegar to brighten dishes and reduce the need for added salt.",
  "Cook with healthy fats like olive oil, avocado oil, or nuts to support nutrient absorption.",
  "Batch cook soups and stews—they freeze well and provide easy healthy meals later.",
  "Measure cooking oil with a teaspoon instead of pouring to control calorie intake.",
  "Sharpen your knife before cooking—a sharp knife is safer and makes prep faster.",
  "Include colorful vegetables at every meal—different colors provide different nutrients.",
  "Store herbs like basil and parsley with stems in water on the counter to keep them fresh.",
  "Plan meals around vegetables first, then add proteins and grains for balanced nutrition.",
  "Use a timer for cooking to avoid burning and maintain consistent results.",
  "Eat protein-rich foods to help maintain muscle mass and keep you feeling full longer.",
  "Clean as you cook to make cleanup easier and reduce stress in the kitchen.",
  "Try new vegetables each week to expand your palate and nutrient variety.",
  "Cook grains in broth instead of water for extra flavor and nutrients.",
  "Pair carbohydrates with protein and fat to slow sugar absorption and maintain energy.",
  "Use an instant-read thermometer to ensure proteins are cooked safely without overcooking.",
  "Opt for whole grains over refined grains for better fiber and nutrient content.",
  "Prep smoothie ingredients in freezer bags for quick, nutritious breakfasts on busy mornings.",
  "Taste your food while cooking and adjust seasonings gradually—you can add but can't take away.",
  "Include fiber-rich foods like beans, whole grains, and vegetables to support digestive health."
];

